export const BASE_URL = 'https://letxchat.takoraditraining.com/api/v1'
export const CHATROOMS_URL = 'https://letxchat.takoraditraining.com/api/v1/chatrooms'
export const CHATROOM_URL = 'https://letxchat.takoraditraining.com/api/v1/chatroom'
export const PUSHER_API_KEY = 'b1b56c7d715d69aa8d64'
export const PUSHER_CLUSTER = 'eu'