export const FILE_URL = 'https://takoraditraining.com/LetXChat/storage/app/public/'
export const BASE_URL = 'https://letxchat.takoraditraining.com/api/v1'
export const CHATROOMS_URL = 'https://letxchat.takoraditraining.com/api/v1/chatrooms'
export const ADMIN_URL = 'https://letxchat.takoraditraining.com/api/v1/admin/login'
export const PUSHER_API_KEY = 'b1b56c7d715d69aa8d64'
export const PUSHER_CLUSTER = 'eu'
